language: node_js
node_js:
  - 8.15.0

before_deploy:
  - yarn
  - yarn build

deploy:
# production
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep_history: true
  local_dir: './build/'
  target_branch: 'master'
  on:
    branch: production

# test
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep_history: true
  local_dir: './build/'
  repo: 'anitab-org/test-anitab-org'
  target_branch: 'master'
  on:
    branch: deply_test

